allow code 20 and 21

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -48,8 +48,10 @@ jobs:
       - name: Run binary and check release need
         id: run_binary
         run: |
+          set +e
           ./target/release/rust-dump "${{ env.last_release_date }}"
           exit_code=$?
+          set -e
 
           if [ $exit_code -eq 0 ]; then
             tar -cf - categories keywords dump | zstd -o data.tar.zst
@@ -59,6 +61,12 @@ jobs:
           if [ $exit_code -eq 0 ] && [ ! -f ./data.tar.zst ]; then
             echo "Error: data.tar.zst artifact not found!"
             exit 1
+          elif [ $exit_code -eq 20 ] || [ $exit_code -eq 21 ]; then
+            echo "Binary exited intentionally with code $exit_code. Skipping release."
+            echo "greater=0" >> $GITHUB_ENV
+          else
+            echo "Unexpected failure with exit code $exit_code"
+            exit $exit_code
           fi
 
           if [ $exit_code -eq 0 ]; then
